### ISSUE TITLE
'plasma5-applets-groupingplasmoid' package should conflict with 'kdeplasma-addons' package

### ISSUE THREAD

**Issue by notuxius** [netrunner-rolling/QA-Bugs#1]
Causing '...exists in filesystem...' errors when installing both.

**Comment by NuLogicSystems** [comment]
This must be a new development, if it conflicted when I created the cd the build would have failed.
I'll take a look to see why this is happening now?

**Comment by NuLogicSystems** [comment]
Update:  I just took a look and Indeed, with plasma 5.10.4 upstream has added the grouping plasmoid to the kdeplasma-addons package. As luck would have it, we did not ship our plasma5-applets-groupingplasmoid package on the ISO. I will remove this package from our repository so that others do not try and install it.

**Comment by NuLogicSystems** [comment]
update: I just took a look and we did not ship the groupingplasmoid on the ISO.
I will remove this package from our repository now so that others do not try and install it.
