### ISSUE TITLE
Unable to install 'ring' package group from netrunner repo

### ISSUE THREAD

**Issue by notuxius** [netrunner-rolling/QA-Bugs#10]
'ring' package group in netrunner repo - 1) libringclient  2) ring-daemon  3) ring-kde - requires 'util-linux-nosystemd' 'libutil-linux-nosystemd' 'libeudev' packages to install - which are in conflict with currently installed packages.

Looks like 'ring' package group in netrunner repo -> depends on 'ring-daemon' package from netrunner repo -> which dependends on 'pjproject-savoirfairelinux' package in netrunner repo -> which in turn depends on 'util-linux-ng' in community repo -> which is 'util-linux-nosystemd' in community repo -> which depends on 'libutil-linux-nosystemd' package. And this package causes conflict and inability to install 'ring' package group.

**Comment by NuLogicSystems** [comment]
Thanks for bringing this to my attention.. I don't use these packages myself, but was asked to add them to the repo. The nosystemd packages are leftovers from the openrc versions of Manjaro. This sub-project has since left the Manjaro community to start their own Distribution. I'll take a look at these packages for their default (systemd) versions and see if I can fix the issue in our repository.
Probably not going to get to this until Friday or Saturday, as I'm out of town for the next few days..

**Comment by NuLogicSystems** [comment]
I need to track down what is calling for these nosystemd packages, these should not be..

**Comment by NuLogicSystems** [comment]
I found the culprit. The pjproject-savoirfairelinux package depends on util-linux-ng. Since the util-linux-ng package no longer exists in the Manjaro repositories, it's pulling util-linux-nosystemd because it has a provides string for util-linux-ng and util-linux does not.

I will begin fixing this and updating all the ring based packages as soon as I get back.

**Comment by NuLogicSystems** [comment]
I've updated the ring-kde package and associated dependencies, ring-kde should now install properly.
